travis:
  secure:
    BINSTAR_TOKEN: FI5CbprCSEe6OejM2SIBNXHz9TWFv2YOEj40wKCw8GCW5NOEg10d8eLr9QxqIqyjcb3aksMWQNdd8VWrfnN0xUjY1aaY2HSyQ5Bl3N95o5lo8pgZWiVjE/GlwfpBlwPoFYwcwtEAMet0r5EjaaapMqZ6aZLdGTyNiL5qop5iqvjZB36czAT143eVCYdfLpoZ36ViyDWLq9GpM01YQu5IUioFGHNrzyfK4vQCIESh8dJk/+4W7sMKHXEzjaBBJp34zHBLsOfj4iskIZI8WiidDBvOr/jzjaYI579QBvHE7R59QjlxC9WYV5NHM+wH9cgwgTcKS7n7bcF85DqlxqOC8bkMiARCrND1g/Y74bAt8RRjkT724HgwCYpXGWHdDEqsiE2+VxNeAClUrj6NiTL/MDb/lp6uyZLJiHQ1dtY2Jn4Gbr8zfrOnqdyce3zaNTuYGU0lWbxhRGVvvR0j1c9hxuikczPul4k1TNZ8iaSZkDDiFDsmawkJnPnTL7GGmB/ZY/OciSz49LOxL5EpPTD3k2OccMN1f0QcE5WEsJwl+ZbAegfRIpQMQVP7J00gH+KHwPjiAAmuVvC0+Fc4pz5gbrlb7/blAlQSdRVw1J2Ley7PM3defBnVG3ANuPX3uoppB6lFWTvGgtqisoJXnOqYCE/M0V3WBz7EQyXQgYgMn34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
